// Substitua o conteúdo em: utils/wordlist.js
const wordlist = [
    // --- CATEGORIAS POPULARES ---
    { word: "MINECRAFT", theme: "Game" }, { word: "VALORANT", theme: "Game" }, { word: "FORTNITE", theme: "Game" },
    { word: "LEAGUE OF LEGENDS", theme: "Game" }, { word: "COUNTER STRIKE", theme: "Game" }, { word: "OVERWATCH", theme: "Game" },
    { word: "ROCKET LEAGUE", theme: "Game" }, { word: "GENSHIN IMPACT", theme: "Game" }, { word: "THE WITCHER", theme: "Game" },
    { word: "CYBERPUNK", theme: "Game" }, { word: "ELDEN RING", theme: "Game" }, { word: "ZELDA", theme: "Game" },
    { word: "MARIO KART", theme: "Game" }, { word: "RED DEAD REDEMPTION", theme: "Game" }, { word: "GRAND THEFT AUTO", theme: "Game" },
    { word: "ASSASSINS CREED", theme: "Game" }, { word: "GOD OF WAR", theme: "Game" }, { word: "FINAL FANTASY", theme: "Game" },
    { word: "POKEMON", theme: "Game" }, { word: "SONIC", theme: "Game" }, { word: "STREET FIGHTER", theme: "Game" },
    { word: "MORTAL KOMBAT", theme: "Game" }, { word: "APEX LEGENDS", theme: "Game" }, { word: "AMONG US", theme: "Game" },
    { word: "FALL GUYS", theme: "Game" }, { word: "STARDEW VALLEY", theme: "Game" }, { word: "TERRARIA", theme: "Game" },
    { word: "BLOONS TD", theme: "Game" }, { word: "DARK SOULS", theme: "Game" }, { word: "SKYRIM", theme: "Game" },

    { word: "O PODEROSO CHEFAO", theme: "Filme" }, { word: "PULP FICTION", theme: "Filme" }, { word: "MATRIX", theme: "Filme" },
    { word: "SENHOR DOS ANEIS", theme: "Filme" }, { word: "STAR WARS", theme: "Filme" }, { word: "VINGADORES", theme: "Filme" },
    { word: "HARRY POTTER", theme: "Filme" }, { word: "JURASSIC PARK", theme: "Filme" }, { word: "TITANIC", theme: "Filme" },
    { word: "FORREST GUMP", theme: "Filme" }, { word: "O REI LEAO", theme: "Filme" }, { word: "TOY STORY", theme: "Filme" },
    { word: "INTERESTELAR", theme: "Filme" }, { word: "A ORIGEM", theme: "Filme" }, { word: "CLUBE DA LUTA", theme: "Filme" },
    { word: "O ILUMINADO", theme: "Filme" }, { word: "DE VOLTA PARA O FUTURO", theme: "Filme" }, { word: "GLADIADOR", theme: "Filme" },
    { word: "CORINGA", theme: "Filme" }, { word: "PARASITA", theme: "Filme" },
    { word: "BREAKING BAD", theme: "Série" }, { word: "GAME OF THRONES", theme: "Série" }, { word: "STRANGER THINGS", theme: "Série" },
    { word: "THE OFFICE", theme: "Série" }, { word: "FRIENDS", theme: "Série" }, { word: "LA CASA DE PAPEL", theme: "Série" },
    { word: "THE WALKING DEAD", theme: "Série" }, { word: "BLACK MIRROR", theme: "Série" }, { word: "THE MANDALORIAN", theme: "Série" },
    { word: "PEAKY BLINDERS", theme: "Série" },

    // --- CATEGORIAS GERAIS ---
    { word: "BALEIA", theme: "Animal" }, { word: "GIRAFA", theme: "Animal" }, { word: "ELEFANTE", theme: "Animal" },
    { word: "CACHORRO", theme: "Animal" }, { word: "HIPOPOTAMO", theme: "Animal" }, { word: "RINOCERONTE", theme: "Animal" },
    { word: "LEAO", theme: "Animal" }, { word: "TIGRE", theme: "Animal" }, { word: "MACACO", theme: "Animal" },
    { word: "JACARE", theme: "Animal" }, { word: "SERPENTE", theme: "Animal" }, { word: "TARTARUGA", theme: "Animal" },
    { word: "GOLFINHO", theme: "Animal" }, { word: "PINGUIM", theme: "Animal" }, { word: "CANGURU", theme: "Animal" },
    { word: "ZEBRA", theme: "Animal" }, { word: "CROCODILO", theme: "Animal" }, { word: "ORNITORRINCO", theme: "Animal" },
    { word: "ESCORPIAO", theme: "Animal" }, { word: "BORBOLETA", theme: "Animal" }, { word: "CARANGUEJO", theme: "Animal" },
    { word: "CAMALEAO", theme: "Animal" }, { word: "LAGARTIXA", theme: "Animal" }, { word: "PAPAGAIO", theme: "Animal" },
    { word: "TUCANO", theme: "Animal" }, { word: "CORUJA", theme: "Animal" }, { word: "AGUIA", theme: "Animal" },
    { word: "LOBO", theme: "Animal" }, { word: "RAPOSA", theme: "Animal" }, { word: "COALA", theme: "Animal" },

    { word: "ABACAXI", theme: "Comida" }, { word: "MELANCIA", theme: "Comida" }, { word: "LARANJA", theme: "Comida" },
    { word: "MORANGO", theme: "Comida" }, { word: "BANANA", theme: "Comida" }, { word: "MANGA", theme: "Comida" },
    { word: "UVA", theme: "Comida" }, { word: "ACEROLA", theme: "Comida" }, { word: "GOIABA", theme: "Comida" },
    { word: "JABUTICABA", theme: "Comida" }, { word: "PIZZA", theme: "Comida" }, { word: "HAMBURGUER", theme: "Comida" },
    { word: "LASANHA", theme: "Comida" }, { word: "ESPAGUETE", theme: "Comida" }, { word: "CHOCOLATE", theme: "Comida" },
    { word: "SORVETE", theme: "Comida" }, { word: "BOLO", theme: "Comida" }, { word: "SUSHI", theme: "Comida" },
    { word: "SOPA", theme: "Comida" }, { word: "SALADA", theme: "Comida" }, { word: "QUEIJO", theme: "Comida" },
    { word: "PUDIM", theme: "Comida" }, { word: "PANQUECA", theme: "Comida" }, { word: "BRIGADEIRO", theme: "Comida" },
    { word: "FEIJOADA", theme: "Comida" }, { word: "STROGONOFF", theme: "Comida" }, { word: "COXINHA", theme: "Comida" },
    { word: "PIPOCA", theme: "Comida" }, { word: "CHURRASCO", theme: "Comida" }, { word: "TAPIOCA", theme: "Comida" },

    { word: "COMPUTADOR", theme: "Objeto" }, { word: "TELEFONE", theme: "Objeto" }, { word: "GELADEIRA", theme: "Objeto" },
    { word: "VIOLAO", theme: "Objeto" }, { word: "RELOGIO", theme: "Objeto" }, { word: "MICROFONE", theme: "Objeto" },
    { word: "CADEIRA", theme: "Objeto" }, { word: "MESA", theme: "Objeto" }, { word: "GARRAFA", theme: "Objeto" },
    { word: "LAMPADA", theme: "Objeto" }, { word: "OCULOS", theme: "Objeto" }, { word: "CANETA", theme: "Objeto" },
    { word: "LIVRO", theme: "Objeto" }, { word: "MOCHILA", theme: "Objeto" }, { word: "FOGAO", theme: "Objeto" },
    { word: "TRAVESSEIRO", theme: "Objeto" }, { word: "MARTELO", theme: "Objeto" }, { word: "CHAVE DE FENDA", theme: "Objeto" },
    { word: "ESCADA", theme: "Objeto" }, { word: "PRATO", theme: "Objeto" }, { word: "GARFO", theme: "Objeto" },
    { word: "COLHER", theme: "Objeto" }, { word: "JANELA", theme: "Objeto" }, { word: "PORTA", theme: "Objeto" },
    { word: "SOFA", theme: "Objeto" }, { word: "CAMA", theme: "Objeto" }, { word: "TESOURA", theme: "Objeto" },
    { word: "PENTE", theme: "Objeto" }, { word: "VASSOURA", theme: "Objeto" }, { word: "TELEVISAO", theme: "Objeto" },

    { word: "MEDICO", theme: "Profissão" }, { word: "ENGENHEIRO", theme: "Profissão" }, { word: "ADVOGADO", theme: "Profissão" },
    { word: "PROFESSOR", theme: "Profissão" }, { word: "PROGRAMADOR", theme: "Profissão" }, { word: "JORNALISTA", theme: "Profissão" },
    { word: "COZINHEIRO", theme: "Profissão" }, { word: "BOMBEIRO", theme: "Profissão" }, { word: "POLICIAL", theme: "Profissão" },
    { word: "ARQUITETO", theme: "Profissão" }, { word: "DENTISTA", theme: "Profissão" }, { word: "VETERINARIO", theme: "Profissão" },
    { word: "MUSICO", theme: "Profissão" }, { word: "ATOR", theme: "Profissão" }, { word: "CIENTISTA", theme: "Profissão" },
    { word: "MOTORISTA", theme: "Profissão" }, { word: "PADEIRO", theme: "Profissão" }, { word: "ELETRICISTA", theme: "Profissão" },
    { word: "PSICOLOGO", theme: "Profissão" }, { word: "DESIGNER", theme: "Profissão" }, { word: "FOTOGRAFO", theme: "Profissão" },
    { word: "ASTRONAUTA", theme: "Profissão" }, { word: "PILOTO", theme: "Profissão" }, { word: "CARPINTEIRO", theme: "Profissão" },
    { word: "JUIZ", theme: "Profissão" }, { word: "ENFERMEIRO", theme: "Profissão" }, { word: "AGRICULTOR", theme: "Profissão" },
    { word: "CABELEIREIRO", theme: "Profissão" }, { word: "MECANICO", theme: "Profissão" }, { word: "PORTEIRO", theme: "Profissão" },

    { word: "BRASIL", theme: "Lugar" }, { word: "ARGENTINA", theme: "Lugar" }, { word: "ESTADOS UNIDOS", theme: "Lugar" },
    { word: "CANADA", theme: "Lugar" }, { word: "MEXICO", theme: "Lugar" }, { word: "PORTUGAL", theme: "Lugar" },
    { word: "ESPANHA", theme: "Lugar" }, { word: "FRANCA", theme: "Lugar" }, { word: "ITALIA", theme: "Lugar" },
    { word: "ALEMANHA", theme: "Lugar" }, { word: "REINO UNIDO", theme: "Lugar" }, { word: "JAPAO", theme: "Lugar" },
    { word: "CHINA", theme: "Lugar" }, { word: "INDIA", theme: "Lugar" }, { word: "AUSTRALIA", theme: "Lugar" },
    { word: "EGITO", theme: "Lugar" }, { word: "AFRICA DO SUL", theme: "Lugar" }, { word: "RUSSIA", theme: "Lugar" },
    { word: "SUECIA", theme: "Lugar" }, { word: "NORUEGA", theme: "Lugar" }, { word: "AMAZONIA", theme: "Lugar" },
    { word: "PANTANAL", theme: "Lugar" }, { word: "DESERTO DO SAARA", theme: "Lugar" }, { word: "MONTE EVEREST", theme: "Lugar" },
    { word: "RIO DE JANEIRO", theme: "Lugar" }, { word: "SAO PAULO", theme: "Lugar" }, { word: "NOVA IORQUE", theme: "Lugar" },
    { word: "LONDRES", theme: "Lugar" }, { word: "PARIS", theme: "Lugar" }, { word: "TOQUIO", theme: "Lugar" },

    { word: "FUTEBOL", theme: "Esporte" }, { word: "BASQUETE", theme: "Esporte" }, { word: "VOLEIBOL", theme: "Esporte" },
    { word: "TENIS", theme: "Esporte" }, { word: "NATACAO", theme: "Esporte" }, { word: "AUTOMOBILISMO", theme: "Esporte" },
    { word: "ATLETISMO", theme: "Esporte" }, { word: "HANDEBOL", theme: "Esporte" }, { word: "SURF", theme: "Esporte" },
    { word: "SKATE", theme: "Esporte" }, { word: "BOXE", theme: "Esporte" }, { word: "JUDO", theme: "Esporte" },
    { word: "GINASTICA", theme: "Esporte" }, { word: "CICLISMO", theme: "Esporte" }, { word: "GOLFE", theme: "Esporte" },
    { word: "RUGBY", theme: "Esporte" }, { word: "HOQUEI", theme: "Esporte" }, { word: "ESGRIMA", theme: "Esporte" },
    { word: "BADMINTON", theme: "Esporte" }, { word: "CANOAGEM", theme: "Esporte" },

    { word: "PARALELEPIPEDO", theme: "Geral" }, { word: "INDEPENDENCIA", theme: "Geral" }, { word: "TECNOLOGIA", theme: "Geral" },
    { word: "DEMOCRACIA", theme: "Geral" }, { word: "LIBERDADE", theme: "Geral" }, { word: "FELICIDADE", theme: "Geral" },
    { word: "CONHECIMENTO", theme: "Geral" }, { word: "CULTURA", theme: "Geral" }, { word: "HISTORIA", theme: "Geral" },
    { word: "CIENCIA", theme: "Geral" }, { word: "UNIVERSO", theme: "Geral" }, { word: "ECONOMIA", theme: "Geral" },
    { word: "POLITICA", theme: "Geral" }, { word: "SAUDADE", theme: "Geral" }, { word: "ALEGRIA", theme: "Geral" },
    { word: "AMIZADE", theme: "Geral" }, { word: "RESPEITO", theme: "Geral" }, { word: "JUSTICA", theme: "Geral" },
    { word: "SUSTENTABILIDADE", theme: "Geral" }, { word: "GLOBALIZACAO", theme: "Geral" }, { word: "FOTOSSINTESE", theme: "Geral" },
    { word: "METEOROLOGIA", theme: "Geral" }, { word: "CARNAVAL", theme: "Geral" }, { word: "ORQUESTRA", theme: "Geral" },
    { word: "BIBLIOTECA", theme: "Geral" }, { word: "AQUARELA", theme: "Geral" }, { word: "DIAMANTE", theme: "Geral" },
    { word: "ELETRICIDADE", theme: "Geral" }, { word: "GRAVIDADE", theme: "Geral" }, { word: "INTERNET", theme: "Geral" },

    { word: "HELICOPTERO", theme: "Veículo" }, { word: "AMBULANCIA", theme: "Veículo" }, { word: "MOTOCICLETA", theme: "Veículo" },
    { word: "BICICLETA", theme: "Veículo" }, { word: "NAVIO", theme: "Veículo" }, { word: "AVIAO", theme: "Veículo" },
    { word: "SUBMARINO", theme: "Veículo" }, { word: "ONIBUS", theme: "Veículo" }, { word: "CAMINHAO", theme: "Veículo" },
    { word: "TRATOR", theme: "Veículo" }, { word: "FOGUETE", theme: "Veículo" }, { word: "CARRO", theme: "Veículo" },
    { word: "TREM", theme: "Veículo" }, { word: "JIPE", theme: "Veículo" }, { word: "IATE", theme: "Veículo" },
    { word: "PATINETE", theme: "Veículo" }, { word: "BONDE", theme: "Veículo" }, { word: "JAGUAR", theme: "Veículo" },
    { word: "MUSTANG", theme: "Veículo" }, { word: "FUSCA", theme: "Veículo" },

    { word: "ASTRONOMIA", theme: "Ciência" }, { word: "MATEMATICA", theme: "Ciência" }, { word: "GEOGRAFIA", theme: "Ciência" },
    { word: "BIOLOGIA", theme: "Ciência" }, { word: "QUIMICA", theme: "Ciência" }, { word: "FISICA", theme: "Ciência" },
    { word: "GEOLOGIA", theme: "Ciência" }, { word: "BOTANICA", theme: "Ciência" }, { word: "ZOOLOGIA", theme: "Ciência" },
    { word: "ECOLOGIA", theme: "Ciência" }, { word: "GENETICA", theme: "Ciência" }, { word: "ROBOTICA", theme: "Ciência" },
    { word: "INFORMATICA", theme: "Ciência" }, { word: "MEDICINA", theme: "Ciência" }, { word: "PSICOLOGIA", theme: "Ciência" },
    { word: "SOCIOLOGIA", theme: "Ciência" }, { word: "FILOSOFIA", theme: "Ciência" }, { word: "ANTROPOLOGIA", theme: "Ciência" },
    { word: "ARQUEOLOGIA", theme: "Ciência" }, { word: "PALEONTOLOGIA", theme: "Ciência" }
];

function getRandomWord() {
    return wordlist[Math.floor(Math.random() * wordlist.length)];
}

module.exports = { getRandomWord };